name: Repo Updater
on: workflow_dispatch
jobs:
  update:
    name: Self-update repository
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        distribution: corretto
        java-version: 21
    - name: Execute update.sh
      run: ./update.sh auto true
